package com.pmq.vnnewsvoice.article.dto.amqp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import java.util.UUID;
import lombok.Data;

/**
 * DTO consumed from queue 'article.events.article-service'. Published by MLService (Phase 1.3) via
 * fanout exchange 'article.events'. camelCase fields match Jackson serialization from Python
 * aio-pika publisher.
 */
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class ArticleEventMessage {

  private UUID articleId; // UUID4 generated by MLService
  private String sourceId; // e.g. "vnexpress"
  private String sourceName; // e.g. "VnExpress"
  private String title;
  private String topImage;
  private String url;
  private String publishedAt; // ISO-8601 string (nullable)
  private String summary;
  private String audioUrl;
  private List<BlockMessage> blocks;
  private String eventType; // "article.created" | "article.updated" | "video.generated"
  private String status; // e.g. "PUBLISHED" | "DELETED"
  private Boolean isActive;
  private String deletedAt; // ISO-8601 string (nullable)
  private String videoUrl; // set only for eventType="video.generated"

  @Data
  @JsonIgnoreProperties(ignoreUnknown = true)
  public static class BlockMessage {
    private int order;
    private String type; // "paragraph" | "heading" | "image"
    private String content;
    private String text;
    private String tag;
    private String src;
    private String alt;
    private String caption;
  }
}
