"""
app/messaging/consumer.py
Consumes from queue 'ml.tasks', runs ML pipeline, publishes to 'article.events' fanout.

Pipeline for each message:
  1. Receive MlTaskMessage from CrawlingService
  2. Summarize article text via ArticleSummarizationService (ViT5 → Gemini → emergency)
  3. Generate TTS audio via ArticleTTSService → upload to S3 → get audioUrl
  4. Assign UUID4 as articleId
  5. Publish ArticleEventMessage to fanout exchange 'article.events'
     ├── article.events.article-service → ArticleService (Phase 1.5)
     └── article.events.rag-service     → RAG Service (Phase 1.4)
"""

import asyncio
import json
import logging
from typing import Optional

from aio_pika import IncomingMessage

from app.messaging.schemas import ArticleEventMessage, MlTaskMessage
from app.messaging.publisher import ArticleEventsPublisher

logger = logging.getLogger(__name__)


class MlTaskConsumer:
    @staticmethod
    def _preview_text(text: str, max_chars: int = 220) -> str:
        """Return a compact single-line preview for logs."""
        normalized = " ".join((text or "").split())
        if len(normalized) <= max_chars:
            return normalized
        return f"{normalized[:max_chars]}..."

    def __init__(self, publisher: ArticleEventsPublisher):
        self._publisher = publisher

    async def handle_message(self, message: IncomingMessage) -> None:
        """Process one ml.tasks message from CrawlingService."""
        async with message.process():  # auto-ack on success, nack on exception
            try:
                body = json.loads(message.body.decode("utf-8"))
                task = MlTaskMessage(**body)
                logger.info(
                    "Received ml.task: source=%s title=%s...",
                    task.sourceId,
                    task.title[:60],
                )
                await self._process(task)
            except Exception:
                logger.exception("Error processing ml.task message")
                raise  # triggers nack

    async def _process(self, task: MlTaskMessage) -> None:
        """Run ML pipeline in thread pool (CPU-bound tasks) then publish."""
        loop = asyncio.get_event_loop()
        from app.core.config import settings

        # Step 1 & 2: Summarize (CPU-bound — run in thread pool)
        summary: Optional[str] = await loop.run_in_executor(None, self._summarize, task)

        # Step 3: TTS (I/O-bound API call — run in thread pool to avoid blocking)
        max_chars = max(settings.TTS_MAX_INPUT_CHARS, 0)
        tts_input, tts_source = self._build_tts_input(task, summary, max_chars)
        logger.info(
            "TTS input prepared: source=%s chars=%d max_chars=%d url=%s preview=%r",
            tts_source,
            len(tts_input),
            max_chars,
            task.url,
            self._preview_text(tts_input),
        )
        audio_url: Optional[str] = await loop.run_in_executor(
            None, self._generate_tts, tts_input
        )

        # Step 4: Build event with auto-generated UUID4
        event = ArticleEventMessage(
            # articleId=uuid4 auto-generated by Field(default_factory=...)
            sourceId=task.sourceId,
            sourceName=task.sourceName,
            title=task.title,
            topImage=task.topImage,
            url=task.url,
            publishedAt=task.publishedAt,
            summary=summary,
            audioUrl=audio_url,
            blocks=task.blocks,
            eventType="article.created",
        )

        # Step 5: Publish to fanout
        await self._publisher.publish(event.model_dump_json())
        logger.info(
            "Published article.events: id=%s source=%s",
            event.articleId,
            event.sourceId,
        )

    @staticmethod
    def _build_tts_input(
        task: MlTaskMessage,
        summary: Optional[str],
        max_content_chars: int,
    ) -> tuple[str, str]:
        """Use content for TTS when size is safe; otherwise prefer summary."""

        summary_text = (summary or "").strip()
        content_text = ""
        content_source = ""

        if task.content and task.content.strip():
            content_text = task.content.strip()
            content_source = "content"
        else:
            paragraphs = [
                (block.text or block.content).strip()
                for block in task.blocks
                if block.type == "paragraph" and (block.text or block.content)
            ]
            if paragraphs:
                content_text = " ".join(paragraphs)
                content_source = "blocks"

        if content_text:
            if max_content_chars and len(content_text) > max_content_chars:
                if summary_text:
                    return summary_text, f"summary_{content_source}_too_long"
                return content_text[
                    :max_content_chars
                ], f"{content_source}_truncated_no_summary"
            return content_text, content_source

        if summary_text:
            return summary_text, "summary"

        return task.title.strip(), "title"

    @staticmethod
    def _summarize(task: MlTaskMessage) -> Optional[str]:
        """Blocking call — runs in executor thread pool."""
        try:
            from app.services.text_summarization import ArticleSummarizationService
            from app.models.article import Article, ArticleBlock

            # Convert message blocks to Article model
            blocks = [
                ArticleBlock(
                    order=b.order,
                    type=b.type,
                    content=b.content,
                    text=b.text,
                    tag=b.tag,
                    src=b.src,
                    alt=b.alt,
                    caption=b.caption,
                )
                for b in task.blocks
            ]
            article = Article(
                title=task.title,
                top_image=task.topImage,
                url=task.url,
                blocks=blocks,
                published_at=task.publishedAt,
                sapo=task.sapo,
            )

            # Run sapo data collection (training data flywheel)
            if task.sapo:
                paragraphs = [
                    b.text or b.content
                    for b in task.blocks
                    if b.type == "paragraph" and (b.text or b.content)
                ]
                ArticleSummarizationService._collect_sapo_pair(
                    " ".join(paragraphs), task.sapo
                )

            summary = ArticleSummarizationService.summarize_article(article)
            logger.info("Summarization done — %d chars", len(summary))
            return summary
        except Exception:
            logger.exception("Summarization failed for url=%s", task.url)
            return None

    @staticmethod
    def _generate_tts(text: str) -> Optional[str]:
        """Blocking call — runs in executor thread pool."""
        try:
            from app.core.config import settings
            from app.services.tts_service import ArticleTTSService

            max_chars = max(settings.TTS_MAX_INPUT_CHARS, 0)
            tts_text = text
            if max_chars and len(text) > max_chars:
                tts_text = text[:max_chars]
                logger.info(
                    "TTS input truncated: original_chars=%d truncated_chars=%d",
                    len(text),
                    len(tts_text),
                )

            result = ArticleTTSService.generate_tts_with_upload_cloudinary(tts_text)

            if result and result.get("audio_url"):
                logger.info("TTS done — url=%s", result["audio_url"])
                return result["audio_url"]
            return None
        except Exception:
            logger.exception("TTS failed")
            return None  # non-critical — article saved without audio
