apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://vnnewsvoice_prometheus:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      scrapeInterval: 15s

  - name: Loki
    type: loki
    uid: loki
    url: http://vnnewsvoice_loki:3100
    access: proxy
    isDefault: false
    editable: false
    jsonData:
      maxLines: 1000
