"""Add parent_chunks table

Revision ID: 4cf697802035
Revises:
Create Date: 2026-02-25 16:16:36.803948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4cf697802035"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parent_chunks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("article_id", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parent_chunks_article_id"),
        "parent_chunks",
        ["article_id"],
        unique=False,
    )
    op.create_index(op.f("ix_parent_chunks_id"), "parent_chunks", ["id"], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f("ix_parent_chunks_id"), table_name="parent_chunks")
    op.drop_index(op.f("ix_parent_chunks_article_id"), table_name="parent_chunks")
    op.drop_table("parent_chunks")
    # ### end Alembic commands ###
